mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8080:80
  volumes:
    - ./volumes/app:/var/www/html
mauticdb:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./volumes/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: example